// Canonical USAEO chapters list (51 entries).
// Source: uploaded chapter list, April 2026.
// Duplicates in source list are preserved intentionally — kept by id suffix.
export const CHAPTERS_SEED = [
  { id: 's1',  school: 'Tottenville High School',               city: 'Staten Island',          state: 'NY', lat: 40.5279,  lng: -74.1956,  status: 'active' },
  { id: 's2',  school: 'High Tech High School',                  city: 'Jersey City',            state: 'NJ', lat: 40.7282,  lng: -74.0776,  status: 'active' },
  { id: 's3',  school: 'Museum High School',                     city: 'New York',               state: 'NY', lat: 40.7794,  lng: -73.9632,  status: 'active' },
  { id: 's4',  school: 'Brooklyn Tech High School',              city: 'Brooklyn',               state: 'NY', lat: 40.6882,  lng: -73.9767,  status: 'active' },
  { id: 's5',  school: 'South Brunswick High School',            city: 'South Brunswick',        state: 'NJ', lat: 40.3915,  lng: -74.5246,  status: 'active' },
  { id: 's6',  school: 'New Hope-Solebury High School',          city: 'New Hope',               state: 'PA', lat: 40.3628,  lng: -74.9513,  status: 'active' },
  { id: 's7',  school: 'Downingtown East High School',           city: 'Exton',                  state: 'PA', lat: 40.0115,  lng: -75.6557,  status: 'active' },
  { id: 's8',  school: 'Weymouth High School',                   city: 'Weymouth',               state: 'MA', lat: 42.2175,  lng: -70.9397,  status: 'active' },
  { id: 's9',  school: 'Green Hope High School',                 city: 'Cary',                   state: 'NC', lat: 35.8236,  lng: -78.8503,  status: 'active' },
  { id: 's10', school: 'Hamilton High School',                   city: 'Chandler',               state: 'AZ', lat: 33.2541,  lng: -111.8234, status: 'active' },
  { id: 's11', school: 'John Champe High School',                city: 'Aldie',                  state: 'VA', lat: 38.9659,  lng: -77.6200,  status: 'active' },
  { id: 's12', school: 'West Boca Raton Community High School',  city: 'Boca Raton',             state: 'FL', lat: 26.3583,  lng: -80.1817,  status: 'active' },
  { id: 's13', school: 'The Frazer School',                      city: 'Gainesville',            state: 'FL', lat: 29.6516,  lng: -82.3248,  status: 'active' },
  { id: 's14', school: 'NCSSM',                                  city: 'Durham',                 state: 'NC', lat: 35.9961,  lng: -78.9014,  status: 'active' },
  { id: 's15', school: 'Lambert High School',                    city: 'Forsyth County',         state: 'GA', lat: 34.1662,  lng: -84.0911,  status: 'active' },
  { id: 's16', school: 'Eastside High School',                   city: 'Gainesville',            state: 'FL', lat: 29.6528,  lng: -82.2937,  status: 'active' },
  { id: 's17', school: 'Stanton College Preparatory',            city: 'Jacksonville',           state: 'FL', lat: 30.3288,  lng: -81.6572,  status: 'active' },
  { id: 's18', school: 'Ravenwood High School',                  city: 'Brentwood',              state: 'TN', lat: 35.9715,  lng: -86.8103,  status: 'active' },
  { id: 's19', school: 'Denmark High School',                    city: 'Forsyth County',         state: 'GA', lat: 34.1421,  lng: -84.1300,  status: 'active' },
  { id: 's20', school: 'Green Level High School',                city: 'Cary',                   state: 'NC', lat: 35.8463,  lng: -78.9134,  status: 'active' },
  { id: 's21', school: 'Hickory Ridge High School',              city: 'Harrisburg',             state: 'NC', lat: 35.3177,  lng: -80.6535,  status: 'active' },
  { id: 's22', school: 'Adlai E. Stevenson High School',         city: 'Buffalo Grove',          state: 'IL', lat: 42.1663,  lng: -87.9806,  status: 'active' },
  { id: 's23', school: 'Adlai E. Stevenson High School',         city: 'Long Grove',             state: 'IL', lat: 42.1818,  lng: -87.9956,  status: 'active' },
  { id: 's24', school: 'Blue Valley North High School',          city: 'Overland Park',          state: 'KS', lat: 38.9293,  lng: -94.6718,  status: 'active' },
  { id: 's25', school: 'Zionsville Community High School',       city: 'Zionsville',             state: 'IN', lat: 39.9645,  lng: -86.2522,  status: 'active' },
  { id: 's26', school: 'Justin Wakeland High School',            city: 'Frisco',                 state: 'TX', lat: 33.1700,  lng: -96.8900,  status: 'active' },
  { id: 's27', school: 'Heritage High School',                   city: 'Frisco',                 state: 'TX', lat: 33.1316,  lng: -96.7910,  status: 'active' },
  { id: 's28', school: 'Coppell High School',                    city: 'Coppell',                state: 'TX', lat: 32.9543,  lng: -97.0150,  status: 'active' },
  { id: 's29', school: 'Obra D. Tompkins High School',           city: 'Katy',                   state: 'TX', lat: 29.7858,  lng: -95.8245,  status: 'active' },
  { id: 's30', school: 'Obra D. Tompkins High School',           city: 'Katy',                   state: 'TX', lat: 29.7858,  lng: -95.8245,  status: 'active' },
  { id: 's31', school: 'Lebanon Trail High School',              city: 'Frisco',                 state: 'TX', lat: 33.1581,  lng: -96.8230,  status: 'active' },
  { id: 's32', school: 'Seven Lakes High School',                city: 'Katy',                   state: 'TX', lat: 29.7258,  lng: -95.8049,  status: 'active' },
  { id: 's33', school: 'Tom Glenn High School',                  city: 'Austin',                 state: 'TX', lat: 30.1710,  lng: -97.8950,  status: 'active' },
  { id: 's34', school: 'Frisco High School',                     city: 'Frisco',                 state: 'TX', lat: 33.1501,  lng: -96.8236,  status: 'active' },
  { id: 's35', school: 'California High School',                 city: 'San Ramon',              state: 'CA', lat: 37.7600,  lng: -121.9550, status: 'active' },
  { id: 's36', school: 'Cupertino High School',                  city: 'Cupertino',              state: 'CA', lat: 37.3187,  lng: -122.0313, status: 'active' },
  { id: 's37', school: 'Los Gatos High School',                  city: 'Los Gatos',              state: 'CA', lat: 37.2278,  lng: -121.9733, status: 'active' },
  { id: 's38', school: 'Cosumnes Oaks High School',              city: 'Elk Grove',              state: 'CA', lat: 38.3969,  lng: -121.3826, status: 'active' },
  { id: 's39', school: 'Mountain House High School',             city: 'Mountain House',         state: 'CA', lat: 37.7810,  lng: -121.5420, status: 'active' },
  { id: 's40', school: 'Western Sierra Collegiate Academy',      city: 'Roseville',              state: 'CA', lat: 38.7896,  lng: -121.2355, status: 'active' },
  { id: 's41', school: 'Chaminade College Preparatory',          city: 'Los Angeles',            state: 'CA', lat: 34.1908,  lng: -118.5736, status: 'active' },
  { id: 's42', school: 'Arcadia High School',                    city: 'Arcadia',                state: 'CA', lat: 34.1297,  lng: -118.0181, status: 'active' },
  { id: 's43', school: 'Dougherty Valley High School',           city: 'San Ramon',              state: 'CA', lat: 37.7492,  lng: -121.9013, status: 'active' },
  { id: 's44', school: 'River Hill High School',                 city: 'Clarksville',            state: 'MD', lat: 39.2032,  lng: -76.9497,  status: 'active' },
  { id: 's45', school: 'North Shore Hebrew Academy High School', city: 'Long Island',            state: 'NY', lat: 40.8176,  lng: -73.7169,  status: 'active' },
  { id: 's46', school: 'Independence High School',               city: 'Frisco',                 state: 'TX', lat: 33.1250,  lng: -96.8550,  status: 'active' },
  { id: 's47', school: 'Lone Star High School',                  city: 'Frisco',                 state: 'TX', lat: 33.1550,  lng: -96.8000,  status: 'active' },
  { id: 's48', school: 'Liberty High School',                    city: 'Frisco',                 state: 'TX', lat: 33.1200,  lng: -96.8200,  status: 'active' },
  { id: 's49', school: 'Centennial High School',                 city: 'Frisco',                 state: 'TX', lat: 33.1450,  lng: -96.7710,  status: 'active' },
  { id: 's50', school: 'Lebanon Trail High School',              city: 'Frisco',                 state: 'TX', lat: 33.1581,  lng: -96.8230,  status: 'active' },
  { id: 's51', school: 'Frisco High School',                     city: 'Frisco',                 state: 'TX', lat: 33.1501,  lng: -96.8236,  status: 'active' },
];

export const CHAPTER_STATE_COUNT = new Set(CHAPTERS_SEED.map(c => c.state)).size;
