// Canonical partner list, shared by Home + Partners pages.
// `wordmark` renders the text next to the logo as a combination mark.
// `tags` are used to filter partners into the three "how they contribute" sections on the Partners page:
//   'academic' | 'awareness' | 'research'
export const PARTNERS = [
  {
    name: 'Stellar',
    logo: '/logos/Stellar.png',
    url: 'https://stellarlearning.app/',
    desc: 'Student learning tools',
    wordmark: { text: 'Stellar\nLearning', fontFamily: 'Inter, sans-serif', fontWeight: 600, fontSize: '0.85rem', wrap: true },
    tags: ['academic'],
  },
  {
    name: 'Crackd',
    logo: '/logos/Crackd.png',
    url: 'https://crackd.it/',
    desc: 'Test prep platform',
    wordmark: { text: 'Crackd', fontFamily: 'Inter, sans-serif', fontWeight: 700 },
    tags: ['academic'],
  },
  {
    name: 'Launchpoint',
    logo: '/logos/Launchpoint.svg',
    url: 'https://www.launchpointhq.com/',
    desc: 'Career launchpad',
    logoScale: 1.5,
    logoCrop: true,
    tags: ['research'],
  },
  {
    name: 'Fintech Scholars',
    logo: '/logos/Fintech-Scholars.png',
    url: 'https://www.fintechscholars.org/',
    desc: 'Financial literacy',
    logoScale: 1.2,
    logoFilter: 'brightness(0.4)',
    wordmark: { text: 'Fintech\nScholars', fontFamily: 'Inter, sans-serif', fontWeight: 600, fontSize: '0.85rem', wrap: true },
    tags: ['awareness'],
  },
  {
    name: 'Think Finance',
    logo: '/logos/Think-Finance.png',
    url: 'https://www.think-finance.org/',
    desc: 'Finance education',
    logoScale: 0.9,
    logoCrop: true,
    wordmark: { text: 'Think\nFinance', fontFamily: 'Inter, sans-serif', fontWeight: 500, fontSize: '0.85rem', wrap: true },
    tags: ['awareness', 'academic'],
  },
  {
    name: 'YRI',
    logo: '/logos/YRI.png',
    url: 'https://www.yriscience.com/',
    desc: 'Youth research institute',
    wordmark: { text: 'YRI\nFellowship', fontFamily: 'Inter, sans-serif', fontWeight: 500, fontSize: '0.85rem', wrap: true },
    tags: ['research'],
  },
  {
    name: 'FYC',
    logo: '/logos/FYC-Logo.png',
    url: 'https://linktr.ee/financialyouthclub',
    desc: 'Financial Youth Club',
    wordmark: { text: 'Financial\nYouth Club', fontFamily: 'Inter, sans-serif', fontWeight: 500, fontSize: '0.85rem', wrap: true },
    tags: ['awareness'],
  },
  {
    name: 'CFE',
    logo: '/logos/CFE.png',
    url: 'https://councilfe.org/',
    desc: 'Council for Financial Education',
    tags: ['awareness', 'academic'],
  },
  {
    name: 'Youth Economy Lab',
    logo: '/logos/YEL.png',
    url: 'https://youtheconomylab.com/',
    desc: 'Student-led economics research',
    wordmark: { text: 'Youth\nEconomy Lab', fontFamily: 'Inter, sans-serif', fontWeight: 500, fontSize: '0.85rem', wrap: true },
    tags: ['research', 'academic'],
  },
  {
    name: 'Synthica',
    logo: '/logos/synthica.png',
    url: 'https://www.synthica.org/',
    desc: 'AI + economics tooling',
    wordmark: { text: 'Synthica', fontFamily: 'Garet, sans-serif', fontWeight: 300 },
    tags: ['research'],
  },
  {
    name: 'A-Warded',
    logo: '/logos/awarded.ico',
    url: 'https://a-warded.org/',
    desc: 'Student awards platform',
    wordmark: { text: 'A-Warded', fontFamily: 'Sora, sans-serif', fontWeight: 600 },
    tags: ['awareness'],
  },
  {
    name: 'Southeast Asian Economics Project',
    shortName: 'SEAE',
    logo: '/logos/seaecon.png',
    url: 'https://seaecon.org/',
    desc: 'Regional economics education',
    wordmark: { text: 'Southeast Asian\nEconomics Project', fontFamily: 'Inter, sans-serif', fontWeight: 500, fontSize: '0.8rem', wrap: true },
    tags: ['research', 'awareness'],
  },
  {
    name: 'NXTHorizon',
    logo: '/logos/NXTHorizon.png',
    url: 'https://www.nxthorizon.org/',
    desc: 'National Finals sponsor network',
    wordmark: { text: 'NXTHorizon', fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace', fontWeight: 700, fontSize: '0.9rem' },
    tags: ['awareness'],
  },
  {
    name: 'YIMO',
    logo: '/logos/YIMO.png',
    url: 'https://www.yimo-official.org/',
    desc: 'IMO-level economics problem creation',
    wordmark: { text: 'Youth International\nMath Olympiad', fontFamily: 'ui-sans-serif, system-ui, sans-serif', fontWeight: 600, fontSize: '0.75rem', wrap: true },
    tags: ['academic'],
  },
];

export const PARTNER_BY_NAME = Object.fromEntries(PARTNERS.map(p => [p.name, p]));
