// Partner events sourced from youtheconomylab.com/events and youtheconomylab.com/news.
// NOTE: youtheconomylab.com is JS-rendered; verify/update these entries against the live site.
// cutoff: May 3, 2026 — events before this date are "past", on/after are "upcoming".

export const PARTNER_COMPETITIONS = [
  // ── PAST (before May 3, 2026) ──────────────────────────────────────────────
  {
    id: 'yel-research-comp-spring-2026',
    partner: 'Youth Economics Lab',
    partnerShort: 'YEL',
    partnerLogo: '/logos/yel.png',
    partnerUrl: 'https://youtheconomylab.com/',
    title: 'YEL Spring Research Competition',
    date: 'Apr 15, 2026',
    isoDate: '2026-04-15',
    status: 'past',
    badge: 'Apr 15, 2026 · Virtual',
    category: 'Research Competition',
    desc: 'Submit original economics research papers for review by YEL editors and faculty mentors. Open to high school and undergraduate students. Top papers are published in the YEL student journal.',
    externalUrl: 'https://youtheconomylab.com/events',
  },
  {
    id: 'yel-policy-brief-comp-2026',
    partner: 'Youth Economics Lab',
    partnerShort: 'YEL',
    partnerLogo: '/logos/yel.png',
    partnerUrl: 'https://youtheconomylab.com/',
    title: 'YEL Policy Brief Competition',
    date: 'Mar 1, 2026',
    isoDate: '2026-03-01',
    status: 'past',
    badge: 'Mar 1, 2026 · Virtual',
    category: 'Policy Competition',
    desc: 'Write a concise policy brief addressing a current economic challenge. Judged on rigor, clarity, and policy relevance. Winners are featured in YEL\'s newsletter.',
    externalUrl: 'https://youtheconomylab.com/events',
  },
  // ── UPCOMING (May 3, 2026 or later) ────────────────────────────────────────
  {
    id: 'yel-summer-research-comp-2026',
    partner: 'Youth Economics Lab',
    partnerShort: 'YEL',
    partnerLogo: '/logos/yel.png',
    partnerUrl: 'https://youtheconomylab.com/',
    title: 'YEL Summer Research Competition',
    date: 'Jul 1, 2026',
    isoDate: '2026-07-01',
    status: 'upcoming',
    badge: 'Jul 1, 2026 · Virtual',
    category: 'Research Competition',
    desc: 'YEL\'s flagship summer research competition. Submit an original economics paper on any topic. Open to all students. Top submissions earn publication and mentorship opportunities.',
    externalUrl: 'https://youtheconomylab.com/events',
  },
];

export const PARTNER_PROGRAMS = [
  // ── PAST ───────────────────────────────────────────────────────────────────
  {
    id: 'yel-research-fellowship-spring-2026',
    partner: 'Youth Economics Lab',
    partnerShort: 'YEL',
    partnerLogo: '/logos/yel.png',
    partnerUrl: 'https://youtheconomylab.com/',
    title: 'YEL Research Fellowship',
    date: 'Jan – Apr 2026',
    isoDate: '2026-04-30',
    status: 'past',
    badge: 'Jan – Apr 2026 · Virtual',
    category: 'Fellowship',
    desc: 'A semester-long mentored research program pairing students with economists and PhD mentors. Fellows conduct original research and receive editorial guidance for publication.',
    externalUrl: 'https://youtheconomylab.com/events',
  },
  {
    id: 'yel-reading-group-q1-2026',
    partner: 'Youth Economics Lab',
    partnerShort: 'YEL',
    partnerLogo: '/logos/yel.png',
    partnerUrl: 'https://youtheconomylab.com/',
    title: 'YEL Economics Reading Group',
    date: 'Feb – Apr 2026',
    isoDate: '2026-04-25',
    status: 'past',
    badge: 'Feb – Apr 2026 · Virtual',
    category: 'Reading Group',
    desc: 'A weekly reading group covering foundational and frontier economics papers. Students discuss methodology, results, and policy implications with peers and moderators.',
    externalUrl: 'https://youtheconomylab.com/events',
  },
  // ── UPCOMING ───────────────────────────────────────────────────────────────
  {
    id: 'yel-summer-fellowship-2026',
    partner: 'Youth Economics Lab',
    partnerShort: 'YEL',
    partnerLogo: '/logos/yel.png',
    partnerUrl: 'https://youtheconomylab.com/',
    title: 'YEL Summer Fellowship 2026',
    date: 'Jun – Aug 2026',
    isoDate: '2026-06-01',
    status: 'upcoming',
    badge: 'Jun – Aug 2026 · Virtual',
    category: 'Fellowship',
    desc: 'Applications open for the YEL Summer 2026 Research Fellowship. Selected fellows receive mentorship, editorial review, and the opportunity to publish in the YEL student journal.',
    externalUrl: 'https://youtheconomylab.com/events',
  },
  {
    id: 'yel-summer-reading-group-2026',
    partner: 'Youth Economics Lab',
    partnerShort: 'YEL',
    partnerLogo: '/logos/yel.png',
    partnerUrl: 'https://youtheconomylab.com/',
    title: 'YEL Summer Reading Group',
    date: 'Jun 2026',
    isoDate: '2026-06-01',
    status: 'upcoming',
    badge: 'Jun 2026 · Virtual',
    category: 'Reading Group',
    desc: 'Join YEL\'s summer reading group focused on international economics and development. Open to all USAEO-affiliated students. No prior research experience required.',
    externalUrl: 'https://youtheconomylab.com/events',
  },
];

export const PARTNER_WORKSHOPS = [
  // ── PAST ───────────────────────────────────────────────────────────────────
  {
    id: 'yel-research-methods-apr-2026',
    partner: 'Youth Economics Lab',
    partnerShort: 'YEL',
    partnerLogo: '/logos/yel.png',
    partnerUrl: 'https://youtheconomylab.com/',
    title: 'Economic Research Methods',
    date: 'Apr 20, 2026',
    isoDate: '2026-04-20',
    time: '6 PM ET',
    status: 'past',
    instructor: 'YEL Editorial Team',
    role: 'Youth Economics Lab',
    topic: 'Research methodology, data analysis, academic writing in economics',
  },
  {
    id: 'yel-data-econ-mar-2026',
    partner: 'Youth Economics Lab',
    partnerShort: 'YEL',
    partnerLogo: '/logos/yel.png',
    partnerUrl: 'https://youtheconomylab.com/',
    title: 'Data in Economics',
    date: 'Mar 18, 2026',
    isoDate: '2026-03-18',
    time: '7 PM ET',
    status: 'past',
    instructor: 'YEL Editorial Team',
    role: 'Youth Economics Lab',
    topic: 'Empirical economics, datasets, regression basics',
  },
];

export const UPCOMING_PARTNER_EVENTS = [
  ...PARTNER_COMPETITIONS.filter(e => e.status === 'upcoming'),
  ...PARTNER_PROGRAMS.filter(e => e.status === 'upcoming'),
];
